=== catalystneuro/ndx-structured-behavior/src/pynwb/tests/BEADL.xsd
<?xml version="1.1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="BEADL">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="BeadlTrialProtocol" type="BeadlTrialProtocolType"/>
            <xs:element name="BeadlEditor" type="BeadlEditorType" minOccurs ="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

<xs:complexType name="BeadlTrialProtocolType">
    <xs:sequence>
        <xs:element name="BeadlArguments">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="BeadlArgument" minOccurs ="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="expression" type="xs:string" use="optional"/>
                            <xs:attribute name="type" use="optional">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="logical" />
                                        <xs:enumeration value="numeric" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="comment" type="xs:string" use="optional"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="HardwareSettings" type="HardwareSettingsType"/>
        <xs:element name="BeadlInputs" type="BeadlInputsType"/>
        <xs:element name="BeadlActions" type="BeadlActionsType"/>
        <xs:element name="BeadlStates" type="BeadlStatesType"/>
        <xs:element name="BeadlStateTransitions" type="BeadlStateTransitionsType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="startState" type="xs:string" use="required"/>
    <xs:attribute name="numberOfTrials" type="xs:double" use="required"/>
</xs:complexType>


<xs:complexType name="HardwareSettingsType">
    <xs:sequence>
        <xs:element name="ConnectionMapping" minOccurs ="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="Value" minOccurs ="0" maxOccurs="1" type="xs:string" />
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="resourceName" type="xs:string" use="required"/>
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="hardware" type="xs:string" use="required"/>
    <xs:attribute name="version" type="xs:string" use="required"/>
    <xs:attribute name="lang" type="xs:string" use="optional"/>
</xs:complexType>

<!-- Definition of BeadlInputs -->
<xs:complexType name="BeadlInputsType">
    <xs:choice maxOccurs="unbounded"> <!-- xs:sequence defines the order and xs:all can't work with unbounded numbers-->
        <xs:element name="HardwareInput" minOccurs ="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:all>
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="connection" type="xs:string" use="required"/>
                <xs:attribute name="type" type="xs:string" use="optional"/>
                <xs:attribute name="comment" type="xs:string" use="optional"/>
            </xs:complexType>
        </xs:element>
        <xs:element name="VirtualInput" minOccurs ="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:all>
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="connection" type="xs:string" use="required"/>
                <xs:attribute name="type" type="xs:string" use="optional"/>
                <xs:attribute name="comment" type="xs:string" use="optional"/>
            </xs:complexType>
        </xs:element>
    </xs:choice>
</xs:complexType>

<!-- Definition of BeadlActions -->
<xs:complexType name="BeadlActionsType">
    <xs:sequence>
        <xs:element name="HardwareAction" minOccurs ="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:all>
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="connection" type="xs:string" use="required"/>
                <xs:attribute name="type" type="xs:string" use="optional"/>
                <xs:attribute name="comment" type="xs:string" use="optional"/>
            </xs:complexType>
        </xs:element>
        <xs:element name="VirtualAction" minOccurs ="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:all>
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="connection" type="xs:string" use="required"/>
                <xs:attribute name="type" type="xs:string" use="optional"/>
                <xs:attribute name="comment" type="xs:string" use="optional"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="BeadlStatesType">
    <xs:sequence>
        <xs:element name="BeadlState" minOccurs ="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="StateTimer" type="xs:string" default="0" />
                    <xs:element name="StateOutputActions">
                        <xs:complexType>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <!-- Definition of OutputAction-->
                                <xs:element name="OutputAction">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="action" type="xs:string" use="required"/>
                                                <xs:attribute name="value" type="xs:string" use="required"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>

                                <!-- Definition of OutputAction-->
                                <xs:element name="SetVariableAction">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="action" type="xs:string" use="required"/>
                                                <xs:attribute name="expression" type="xs:string" use="required"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="StateEvents">
                        <xs:complexType>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">

                                <!-- Definition of TimerEvent-->
                                <xs:element name="TimerEvent">
                                    <xs:complexType>
                                        <xs:attribute name="timer" type="xs:string" use="required"/>
                                        <xs:attribute name="eventname" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>

                                <!-- Definition of ExternalEvent-->
                                <xs:element name="ExternalEvent">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="source" type="xs:string" use="required"/>
                                                <xs:attribute name="eventname" type="xs:string" use="required"/>
                                                <xs:attribute name="value" type="xs:string" use="required"/>
                                                <xs:attribute name="gracePeriod" type="xs:double" use="optional"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>

                                <!-- Definition of ArgumentEvent-->
                                <xs:element name="ArgumentEvent">
                                    <xs:complexType>
                                        <xs:simpleContent> <!-- ToDo: don't know if it needs to be like this since it has no content -->
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="eventname" type="xs:string" use="required"/>
                                                <xs:attribute name="source" type="xs:string" use="required"/>
                                                <xs:attribute name="expression" type="xs:string" use="required"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>

                                <!-- Definition of VariableEvent-->
                                <xs:element name="VariableEvent">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="eventname" type="xs:string" use="required"/>
                                                <xs:attribute name="source" type="xs:string" use="required"/>
                                                <xs:attribute name="expression" type="xs:string" use="required"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>

                                <!-- Definition of TimeSpanEvent-->
                                <xs:element name="TimeSpanEvent">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="eventname" type="xs:string" use="required"/>
                                                <xs:attribute name="source" type="xs:string" use="required"/>
                                                <xs:attribute name="expression" type="xs:string" use="required"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                                
                                <!-- Definition of VirtualEvent - a more generic way of dealing with virtual events!-->
                                <xs:element name="VirtualEvent">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="eventname" type="xs:string" use="required"/>
                                                <xs:attribute name="eventType" type="xs:string" use="required"/>
                                                <xs:attribute name="source" type="xs:string" use="required"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>

                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="BeadlStateTransitionsType">
    <xs:sequence>
        <xs:element name="BeadlStateTransition" minOccurs ="1" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    <xs:element name="Dependency" minOccurs ="0" maxOccurs="1" type="DependencyType" />
                </xs:all>
                <xs:attribute name="from" type="xs:string" use="required"/>
                <xs:attribute name="to" type="xs:string" use="required"/>
                <xs:attribute name="eventname" type="xs:string" use="required"/>
                <xs:attribute name="label" type="xs:string" use="optional"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="DependencyType">
    <xs:attribute name="type" use="required" >
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="BeadlArgumentDependency" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="expression" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="BeadlEditorType">
    <!-- Not implemented yet, should just have a placeholde for an SVG!?! -->
</xs:complexType>
</xs:schema>

=== catalystneuro/ndx-structured-behavior/src/pynwb/tests/LightChasingTask.xml
<?xml version="1.0" encoding="utf-8"?>
<BEADL version="0.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BEADL.xsd">
    <BeadlTrialProtocol name="LightChasingTask" startState="WaitForPoke" numberOfTrials="INF">
        <BeadlArguments>
            <BeadlArgument name="CorrectPortNum" expression="randi(3)" comment="random integer value in range [1..3] to define the port to be used as correct port" type="numeric"/>
            <BeadlArgument name="RewardSize" expression="10" comment="reward size in microliter" type="numeric"/>
            <BeadlArgument name="ValveTime" expression="GetValveTime(RewardSize, ValveTime)" comment="convert the reward size into a duration the reward valve needs to be opened" type="numeric"/>
            <BeadlArgument name="TimeOutDuration" expression="6" comment="Time out duration when the subject selected the wrong port" type="numeric"/>
            <BeadlArgument name="ITIDuration" expression="6" comment="Inter-Trial-Interval" type="numeric"/>
        </BeadlArguments>
        <HardwareSettings hardware="Bpod" version="r0.5">
            <ConnectionMapping name="CorrectPort" resourceName="port1" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 1"/>
            </ConnectionMapping>
            <ConnectionMapping name="CorrectPort" resourceName="port2" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 2"/>
            </ConnectionMapping>
            <ConnectionMapping name="CorrectPort" resourceName="port3" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 3"/>
            </ConnectionMapping>
            <ConnectionMapping name="ErrorPort1" resourceName="port2" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 1"/>
            </ConnectionMapping>
            <ConnectionMapping name="ErrorPort2" resourceName="port3" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 1"/>
            </ConnectionMapping>
            <ConnectionMapping name="ErrorPort1" resourceName="port1" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 2"/>
            </ConnectionMapping>
            <ConnectionMapping name="ErrorPort2" resourceName="port3" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 2"/>
            </ConnectionMapping>
            <ConnectionMapping name="ErrorPort1" resourceName="port1" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 3"/>
            </ConnectionMapping>
            <ConnectionMapping name="ErrorPort2" resourceName="port2" type="behavioralPort">
                <Dependency type="BeadlArgumentDependency" expression="CorrectPortNum == 3"/>
            </ConnectionMapping>
        </HardwareSettings>
        <BeadlInputs>
            <HardwareInput name="CorrectPortPoke" connection="CorrectPort.poke" type="" comment=""/>
            <HardwareInput name="ErrorPort1Poke" connection="ErrorPort1.poke" type="" comment=""/>
            <HardwareInput name="ErrorPort2Poke" connection="ErrorPort2.poke" type="" comment=""/>
        </BeadlInputs>
        <BeadlActions>
            <HardwareAction name="CorrectPortLED" connection="CorrectPort.led" type="" comment=""/>
            <HardwareAction name="CorrectPortValve" connection="CorrectPort.valve" type="" comment=""/>
        </BeadlActions>
        <BeadlStates>
            <BeadlState name="WaitForPoke">
                <StateTimer>inf</StateTimer>
                <StateOutputActions>
                    <OutputAction action="CorrectPortLED" value="on"/>
                </StateOutputActions>
                <StateEvents>
                    <ExternalEvent source="CorrectPortPoke" eventname="CorrectPortPoke_in" value="in"/>
                    <ExternalEvent source="ErrorPort1Poke" eventname="ErrorPort1Poke_in" value="in"/>
                    <ExternalEvent source="ErrorPort2Poke" eventname="ErrorPort2Poke_in" value="in"/>
                </StateEvents>
            </BeadlState>
            <BeadlState name="End">
                <StateTimer>inf</StateTimer>
                <StateOutputActions/>
                <StateEvents/>
            </BeadlState>
            <BeadlState name="Reward">
                <StateTimer>ValveTime</StateTimer>
                <StateOutputActions>
                    <OutputAction action="CorrectPortValve" value="open"/>
                </StateOutputActions>
                <StateEvents>
                    <TimerEvent eventname="stateExpired" timer="StateTimer"/>
                </StateEvents>
            </BeadlState>
            <BeadlState name="ITI">
                <StateTimer>ITIDuration</StateTimer>
                <StateOutputActions/>
                <StateEvents>
                    <TimerEvent eventname="stateExpired" timer="StateTimer"/>
                </StateEvents>
            </BeadlState>
            <BeadlState name="TimeOut">
                <StateTimer>TimeOutDuration</StateTimer>
                <StateOutputActions/>
                <StateEvents>
                    <TimerEvent eventname="stateExpired" timer="StateTimer"/>
                </StateEvents>
            </BeadlState>
        </BeadlStates>
        <BeadlStateTransitions>
            <BeadlStateTransition from="Reward" to="ITI" eventname="stateExpired" label=""/>
            <BeadlStateTransition from="WaitForPoke" to="Reward" eventname="CorrectPortPoke_in" label=""/>
            <BeadlStateTransition from="WaitForPoke" to="TimeOut" eventname="ErrorPort1Poke_in" label=""/>
            <BeadlStateTransition from="WaitForPoke" to="TimeOut" eventname="ErrorPort2Poke_in" label=""/>
            <BeadlStateTransition from="TimeOut" to="ITI" eventname="stateExpired" label=""/>
            <BeadlStateTransition from="ITI" to="End" eventname="stateExpired" label=""/>
        </BeadlStateTransitions>
    </BeadlTrialProtocol>
</BEADL>
